### ISSUE TITLE
HWTest needs to double-sync the ir_data signal on V2 hardware

### ISSUE THREAD

**Issue by robinsonb5** [pwsoft/fpga_examples#4]
On V2 hardware the ir_data signal is asynchronous, which causes the state machine in the cdtv_remote module to get wedged fairly quickly.  The result is that while the IR indicator flickers in response to the remote, the joypad and buttons aren't reliably reported in the hwtest core.
The signal needs to be double-sychronised before being fed into the chameleon2_io module.

**Comment by pwsoft** [comment]
Added extra synchronization flipflop in chameleon_cdtv_remote entity. Please check if this resolves the issue.

**Comment by robinsonb5** [comment]
Yes, that fixes the problem - thanks.
